server:
  port: 8769
spring:
  application:
    name: spring-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: admin-feign
    api-b:
      path: /api/b/**
      serviceId: admin-ribbon